### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/raid/huangsh/datasets/horse2zebra'

### ISSUE THREAD

**Issue by Chanarin** [EMI-Group/SoloGAN#1]
Thnak you so much for your contriutions. I get this error when I try to run training command on windows 11, Python 3. Please help...

------------ Options -------------
Add_CIN_CE: False
Add_CIN_SE: True
D_lr: 0.0002
G_lr: 0.0002
batchSize: 1
c_gan_mode: lsgan
c_num: 8
checkpoints_dir: /checkpoints
continue_train: False
crop_size: 256
d_num: 2
dataroot: /raid/huangsh/datasets
dir_name: SNEG_cls_100
dis_nums: 6
display_freq: 100
display_id: 1
display_port: 8000
display_winsize: 256
e_blocks: 6
format: png
gpu: 10
img_size: 286
init_type: xavier
input_nc: 3
isTrain: True
lambda_c: 1.0
lambda_cyc: 10.0
lambda_rec: 10.0
lambda_vgg: 10.0
nThreads: 4
name: horse2zebra
ndf: 64
nef: 64
ngf: 64
niter: 50
niter_decay: 50
no_html: False
norm: instance
output_nc: 3
print_freq: 200
save_epoch_freq: 20
save_latest_freq: 3000
up_paired: False
up_type: Trp
update_html_freq: 300
which_epoch: latest
-------------- End ----------------
Start preprocessing dataset..!
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    data_loader = CreateDataLoader(opt)
  File "D:\SoloGAN\data\dataloader.py", line 13, in CreateDataLoader
    dataset = UpPairedDataset(opt.dataroot, opt.crop_size, opt.img_size, opt.isTrain, sourceD=sourceD, format=opt.format)
  File "D:\SoloGAN\data\dataloader.py", line 29, in __init__
    self.preprocess()
  File "D:\SoloGAN\data\dataloader.py", line 61, in preprocess
    dirs = os.listdir(self.image_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/raid/huangsh/datasets/horse2zebra'

**Comment by Chanarin** [comment]
I solved this by changing the path in dataroot in base_options.py file.
